### ISSUE TITLE
not recieveing key 

### ISSUE THREAD

**Issue by moneyboy233** [GSRHackZ/EdgyBot_edgenuity-nuke#10]
ii followed all steps, still no key !!! its been a few days.... i did the star method .

**Comment by picoko2** [comment]
> ii followed all steps, still no key !!! its been a few days.... i did the star method .

u have to wait on the purchase site any where from 1-15 minutes to get the key

**Comment by GSRHackZ** [comment]
Key ahs been emailed. Please follow instructions next time 🙏
