### ISSUE TITLE
nothing works

### ISSUE THREAD

**Issue by 24johnjay** [GSRHackZ/EdgyBot_edgenuity-nuke#14]
anytime you try to do a quiz or assignment or anything with the program running it sends you to pick a class all over again. And theirs no way to start edgybot on anything besides fully afk, because the "start" button doesn't show up

**Comment by GSRHackZ** [comment]
You have to select the class using the menu when it's on the dashboard. Then it will open that class for you and ask you to pick an activity type. You select the activity type using the menu and click ok,

**Comment by 24johnjay** [comment]
I do that but I don’t get a button to start edgy bot. I used to but now I
don’t and when I click an activity it refreshes the page back to the
dashboard.

**Comment by GSRHackZ** [comment]
make sure your screen is full screen, the button is always displayed when your inside a class. Also you don't pick an activity using the website buttons, you use the menu. 

Contact me on instagram for better support, this is the best I can do here without any visual to better help me understand your issue
