### ISSUE TITLE
Bug: EdgyBot AutoAnswer cannot complete questions with multiple answers

### ISSUE THREAD

**Issue by FermentedSpiderEye** [GSRHackZ/EdgyBot_edgenuity-nuke#15]
Script Version: v2.08

AutoAnswer successfully opens a brainly popup and searches for an answer, but cannot input multiple answers into edgenuity.
Note: I've once seen AutoAnswer input only one checkbox before, but the question requires multiple answer choices.

This would also include questions with multiple dropdown boxes

https://user-images.githubusercontent.com/115752322/197365298-8f3a5980-070e-49f6-8984-b063588cd64f.mp4

**Comment by GSRHackZ** [comment]
I will look into this when November comes along. I'm extremely busy with tests (The SAT mainly) at the moment, but please keep the issues coming in so I know what to fix/add in the next major update (v3.0). Thank you very much for your very detailed issue reports.  🙏🙏

**Comment by ericpalmer88** [comment]
I have the same issue with the multiple questions, The script has been great man so thank you for that i really appreciate it. Another issue i found was the questions during instruction and assignments it seems to only work for the quiz or unit test.

**Comment by GSRHackZ** [comment]
It was only made for those. Instruction gets done by Edgy AFK mode. (its not graded)

Assignment support will be added after I finish my SAT
