### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by HaileeD8256** [GSRHackZ/EdgyBot_edgenuity-nuke#17]
Each time EdgyBot completes an automated assignment it takes you back to the home screen and you have to keep clicking on the class you want it to do after each assignment.

**Comment by GSRHackZ** [comment]
> Each time EdgyBot completes an automated assignment it takes you back to the home screen and you have to keep clicking on the class you want it to do after each assignment.

You need to select the class and activity using the menu. Not selecting the website elements. Use the drop-down menu on the edgyMenu and select your class from the there. 👌
