### ISSUE TITLE
Feature Request & Review: Honestly, I was hella skeptical but this is amazing. Please add a review page on the website or something, a lot of ppl are missing out

### ISSUE THREAD

**Issue by segsmachine** [GSRHackZ/EdgyBot_edgenuity-nuke#19]
Someone's probably going to accuse me of being a bot. However, since my account has a bit of activity, I'm more hopeful

Ngl, I was skeptical asf when I saw this on Reddit. Immediately thought it was a scam and did everything manually with EdgenTweaks but, please, please, please try it out for yourselves

Also, EdgyPlus team, please add a reviews page or something, it would definitely help

**Comment by GSRHackZ** [comment]
We definitely should add a reviews page. At the moment most of us are busy, especially me the lead dev. By mid November, We should have dealt with all our outside real life issues and edgyBot & edgeplus updates will commence. New features for the bot and the website.  Thanks for the review 🙏🙏
