### ISSUE TITLE
instruction

### ISSUE THREAD

**Issue by picoko2** [GSRHackZ/EdgyBot_edgenuity-nuke#22]
for some of my instructions i have to answer a question where i have to drag it doesn't answer the question it just keeps refreshing the same page also congrats on 500 stars

**Comment by GSRHackZ** [comment]
Thank you 🙏

Regrading the issue with certain questions, please email me pictures of those question types so I can have it fixed in an upcoming script update.

Personal Email: gsrhackz@gmail.com
EdgePlus Email: sedgenuity@gmail.com
