### ISSUE TITLE
Bot keeps refreshing and not working after you get voice message from incorrect answer

### ISSUE THREAD

**Issue by percfeind** [GSRHackZ/EdgyBot_edgenuity-nuke#23]
![52941226-1B5C-42A0-8370-FD2D48381120](https://user-images.githubusercontent.com/117326474/200491198-bcd9dae3-4e63-4786-8fb6-de933caf378c.jpeg)
I know instructions aren’t graded n stuff but after the bot answers a double sided question and it’s incorrect, a voice message plays, after that it just keeps refreshing while it tries to answer the question and the voice message tries to play again and it refreshes and it does that forever

**Comment by GSRHackZ** [comment]
Please contact me on instagram
My user is gsrhackz

Thanks for letting me know.
