### ISSUE TITLE
answering

### ISSUE THREAD

**Issue by ltzTTV** [GSRHackZ/EdgyBot_edgenuity-nuke#5]
it just got all the answers wrong and just brought my grade down

**Comment by ltzTTV** [comment]
well ever since the auto answer script i used stopped working like over a
week ago because edgenuity updated their system, i have been looking for a
new script and i found this one, but i guess it doesnt auto answer anything
correctly, and i just got it updated to the 2.0.1, then i tried it again
and it basically renders as useless if it doesnt auto answer.

**Comment by GSRHackZ** [comment]
it auto answers everything incorrectly for activities that aren't graded. This is made for progressing through the user's course-line of choice. There's no need for it to answer questions correctly (for activities that aren't even graded). For other assignments such as tests & quizzes it uses auto brainly search to display the brainly answers for you on your screen.
