### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by deeznutsyomama11** [GSRHackZ/EdgyBot_edgenuity-nuke#6]
I just got it and ive tried to open it up on the dashboard by doing CTRL ALT M and it doesnt open. Ive seen the interface pop up once when i first got it but now it wont show. Also, when i have the script enabled and i click on my edgenuity activity it kicks me out back into the login page.

**Comment by deeznutsyomama11** [comment]
I got it to open now but everytime i click next activity it just logs me out

**Comment by Bunr33** [comment]
I had that same issue earlier. I just closed out of edgenuity, and turned off EdgyBot on Tampermonkey, and turned it back on.

**Comment by deeznutsyomama11** [comment]
> I had that same issue earlier. I just closed out of edgenuity, and turned off EdgyBot on Tampermonkey, and turned it back on.

Yeah i just figured out how to actually start the bot but when i started it it went a crazy for a bit then it logged me out.

**Comment by picoko2** [comment]
where do you get the key from they email it to you?

**Comment by Bunr33** [comment]
The owner would either check your request on their own time or message them yourself, like on Instagram.

**Comment by picoko2** [comment]
> The owner would either check your request on their own time or message them yourself, like on Instagram.

I got the key now but does it doesnt go on to the next task you have to do that mannualy or is mine just wack?

**Comment by GSRHackZ** [comment]
Hello, what seems to be the issue here?

**Comment by GSRHackZ** [comment]
> > The owner would either check your request on their own time or message them yourself, like on Instagram.
> 
> I got the key now but does it doesnt go on to the next task you have to do that mannualy or is mine just wack?

Did you open the menu using CTRL ALT M and then select a class and activity from the menu?

**Comment by picoko2** [comment]
> Did you open the menu using CTRL ALT M and then select a class and activity from the menu?

yes  after i selected it the class it didnt go on to the next task it just stayed on the one that was completed

**Comment by GSRHackZ** [comment]
> 
> 
> > Did you open the menu using CTRL ALT M and then select a class and activity from the menu?
> 
> 
> 
> yes  after i selected it the class it didnt go on to the next task it just stayed on the one that was completed
> 
> 

Contact @gsrhackz on instagram for more support. Imma need photos or vids of it acting up so I can better understand the issue. Thank you very much 🙏
