### ISSUE TITLE
Brainly

### ISSUE THREAD

**Issue by Bunr33** [GSRHackZ/EdgyBot_edgenuity-nuke#7]
Whenever EdgyBot is unable to answer a question, I would just look it up on Brainly. But since EdgyBot has access to my Brainly, it just automatically chooses the first question it sees, even though it's wrong, and won't let me pick the other questions. 
That goes along with Edgybot giving me wrong answers, and I can not fact-check them as I don't know the topic and now don't have control over my Brainly.

**Comment by GSRHackZ** [comment]
Hello, you seem to have resolved this issue yourself?

**Comment by GSRHackZ** [comment]
We will be updating our brainly auto search or replacing it with a new function we are working on. It will use b2a() - brainly auto answer, in which it will search the answers on brainly and auto answer each question based on the results
