### ISSUE TITLE
The menu is stuck on a class and i cant choose another

### ISSUE THREAD

**Issue by jhendrixx0** [GSRHackZ/EdgyBot_edgenuity-nuke#8]
I stopped the bot and was switching to my ela class and it froze and is now stuck on the class and i cant change it, I’ve restarted my pc , tamper monkey etc

**Comment by GSRHackZ** [comment]
You must be on mac right? Update to the latest version, v2.0.3. We have added mac support for opening and closing the menu with the keybinds
